import pandas as pd
import numpy as np

#headers
#[Date Rptd, DATE OCC, AREA NAME, Crm Cd Desc, Mocodes, Status Desc, LAT, LON]

#tipos de crime, filtrado através de df["Crm Cd Desc"].unique()
CrmCdDesc = ['VEHICLE - STOLEN', 'BURGLARY FROM VEHICLE', 'BIKE - STOLEN',
 'SHOPLIFTING-GRAND THEFT ($950.01 & OVER)', 'THEFT OF IDENTITY',
 'BATTERY - SIMPLE ASSAULT',
 'SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO ANUS OTH',
 'CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 YRS OLDER)',
 'SEX,UNLAWFUL(INC MUTUAL CONSENT, PENETRATION W/ FRGN OBJ',
 'ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT',
 'LETTERS, LEWD  -  TELEPHONE CALLS, LEWD',
 'THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD',
 'CRIMINAL THREATS - NO WEAPON DISPLAYED',
 'EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)',
 'THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)',
 'CHILD ANNOYING (17YRS & UNDER)', 'THEFT PLAIN - PETTY ($950 & UNDER)',
 'INTIMATE PARTNER - SIMPLE ASSAULT', 'LEWD CONDUCT',
 'THEFT PLAIN - ATTEMPT', 'BURGLARY',
 'THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND OVER)', 'ROBBERY',
 'BUNCO, GRAND THEFT', 'BATTERY WITH SEXUAL CONTACT',
 'INTIMATE PARTNER - AGGRAVATED ASSAULT', 'ORAL COPULATION',
 'UNAUTHORIZED COMPUTER ACCESS', 'VIOLATION OF RESTRAINING ORDER',
 'SHOPLIFTING - PETTY THEFT ($950 & UNDER)',
 'VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)',
 'OTHER MISCELLANEOUS CRIME', 'BRANDISH WEAPON',
 'DOCUMENT FORGERY / STOLEN FELONY',
 'SEX OFFENDER REGISTRANT OUT OF COMPLIANCE', 'RAPE, FORCIBLE',
 'VANDALISM - MISDEAMEANOR ($399 OR UNDER)',
 'CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT',
 'CREDIT CARDS, FRAUD USE ($950.01 & OVER)',
 'THREATENING PHONE CALLS/LETTERS', 'SEXUAL PENETRATION W/FOREIGN OBJECT',
 'EXTORTION', 'OTHER ASSAULT', 'PICKPOCKET', 'ARSON', 'DISTURBING THE PEACE']

df = pd.read_csv('dataset.csv', sep=';')

print(df[["Date Rptd", "DATE OCC", "AREA NAME", "Crm Cd Desc", "Mocodes", "Status Desc", "LAT", "LON"]])

df['DATE OCC'] = pd.to_datetime(df['DATE OCC'], format="mixed")
print(df["DATE OCC"].unique())